"""Run automated frame-time and memory profiling for VoidBreaker.

This script supports source-mode and packaged-mode profiling by launching the game
with a dedicated environment-gated stress mode. It records frame-time metrics from
application output JSON and samples process memory at a fixed interval.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import statistics
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path

import psutil

ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_APP_BINARY = (
    ROOT_DIR / "dist" / "VoidBreaker.app" / "Contents" / "MacOS" / "VoidBreaker"
)
DEFAULT_OUTPUT_DIR = ROOT_DIR / "docs" / "performance-data"


@dataclass(slots=True)
class FrameMetrics:
    """Frame-time metrics generated by in-app stress mode."""

    duration_seconds: float
    frame_count: int
    frame_time_min_ms: float
    frame_time_max_ms: float
    frame_time_mean_ms: float
    frame_time_median_ms: float
    frame_time_p95_ms: float
    frame_time_p99_ms: float
    fps_mean: float
    fps_min: float
    fps_max: float


@dataclass(slots=True)
class MemoryMetrics:
    """Memory metrics sampled from the profiled process."""

    sample_count: int
    initial_rss_mb: float
    peak_rss_mb: float
    final_rss_mb: float
    growth_rss_mb: float
    slope_mb_per_min: float
    leak_detected: bool


@dataclass(slots=True)
class ProfileRunResult:
    """Combined profiling outputs for one run mode."""

    mode: str
    exit_code: int
    frame_metrics: FrameMetrics
    memory_metrics: MemoryMetrics
    frame_metrics_path: Path
    memory_csv_path: Path


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for profiling execution."""
    parser = argparse.ArgumentParser(description="Profile VoidBreaker performance")
    parser.add_argument(
        "--mode",
        choices=["source", "packaged", "both"],
        default="both",
        help="Which run mode to profile.",
    )
    parser.add_argument(
        "--source-duration",
        type=float,
        default=60.0,
        help="Stress duration (seconds) for source mode.",
    )
    parser.add_argument(
        "--packaged-duration",
        type=float,
        default=60.0,
        help="Stress duration (seconds) for packaged mode.",
    )
    parser.add_argument(
        "--memory-duration",
        type=float,
        default=1800.0,
        help="Memory sampling duration in seconds (30+ minutes recommended).",
    )
    parser.add_argument(
        "--memory-interval",
        type=float,
        default=1.0,
        help="Memory sampling interval in seconds.",
    )
    parser.add_argument(
        "--app-binary",
        type=Path,
        default=DEFAULT_APP_BINARY,
        help="Path to packaged app executable.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for profiling artifacts.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=1337,
        help="Random seed for deterministic stress-scene generation.",
    )
    return parser.parse_args()


def run_profile(
    mode: str,
    duration_seconds: float,
    memory_duration_seconds: float,
    memory_interval_seconds: float,
    output_dir: Path,
    app_binary: Path,
    seed: int,
) -> ProfileRunResult:
    """Run one profiling mode and collect frame/memory outputs."""
    output_dir.mkdir(parents=True, exist_ok=True)
    frame_json_path = output_dir / f"{mode}-frame-metrics.json"
    memory_csv_path = output_dir / f"{mode}-memory.csv"

    if frame_json_path.exists():
        frame_json_path.unlink()
    if memory_csv_path.exists():
        memory_csv_path.unlink()

    command = build_command(mode=mode, app_binary=app_binary)
    env = os.environ.copy()
    env["VOIDBREAKER_PERF_MODE"] = "1"
    env["VOIDBREAKER_PERF_DURATION"] = str(max(1.0, duration_seconds))
    env["VOIDBREAKER_PERF_OUTPUT"] = str(frame_json_path)
    env["VOIDBREAKER_PERF_SEED"] = str(seed)

    process = subprocess.Popen(
        command,
        cwd=ROOT_DIR,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    monitor_memory(
        pid=process.pid,
        output_csv_path=memory_csv_path,
        max_duration_seconds=max(duration_seconds, memory_duration_seconds),
        sample_interval_seconds=memory_interval_seconds,
    )

    stdout, _ = process.communicate(timeout=30)
    if stdout.strip():
        print(f"\n[{mode}] process output:\n{stdout}")

    if process.returncode != 0:
        raise RuntimeError(f"{mode} run failed with exit code {process.returncode}")
    if not frame_json_path.exists():
        raise RuntimeError(
            f"{mode} run did not produce frame metrics at {frame_json_path}"
        )

    frame_metrics = parse_frame_metrics(frame_json_path)
    memory_metrics = parse_memory_metrics(memory_csv_path)
    return ProfileRunResult(
        mode=mode,
        exit_code=process.returncode,
        frame_metrics=frame_metrics,
        memory_metrics=memory_metrics,
        frame_metrics_path=frame_json_path,
        memory_csv_path=memory_csv_path,
    )


def build_command(mode: str, app_binary: Path) -> list[str]:
    """Build process launch command for source or packaged profiling."""
    if mode == "source":
        return [sys.executable, "-m", "asterax.app.src.main"]
    if not app_binary.exists():
        raise FileNotFoundError(
            f"Packaged app binary not found: {app_binary}. Build with ./scripts/build_app.sh first."
        )
    return [str(app_binary)]


def monitor_memory(
    pid: int,
    output_csv_path: Path,
    max_duration_seconds: float,
    sample_interval_seconds: float,
) -> None:
    """Sample process memory usage at a fixed interval and write CSV."""
    process = psutil.Process(pid)
    started = time.monotonic()
    rows: list[tuple[float, int, int]] = []

    while True:
        now = time.monotonic()
        elapsed = now - started
        if elapsed > max_duration_seconds:
            break

        if not process.is_running():
            break

        try:
            mem = process.memory_info()
            rows.append((elapsed, mem.rss, mem.vms))
        except psutil.Error:
            break

        time.sleep(max(0.1, sample_interval_seconds))

    output_csv_path.parent.mkdir(parents=True, exist_ok=True)
    with output_csv_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["elapsed_seconds", "rss_bytes", "vms_bytes"])
        writer.writerows(rows)


def parse_frame_metrics(path: Path) -> FrameMetrics:
    """Parse frame metrics JSON generated by combat stress mode."""
    payload = json.loads(path.read_text(encoding="utf-8"))
    frame_time = payload["frame_time_ms"]
    fps = payload["fps"]
    return FrameMetrics(
        duration_seconds=float(payload.get("duration_seconds", 0.0)),
        frame_count=int(payload.get("frame_count", 0)),
        frame_time_min_ms=float(frame_time.get("min", 0.0)),
        frame_time_max_ms=float(frame_time.get("max", 0.0)),
        frame_time_mean_ms=float(frame_time.get("mean", 0.0)),
        frame_time_median_ms=float(frame_time.get("median", 0.0)),
        frame_time_p95_ms=float(frame_time.get("p95", 0.0)),
        frame_time_p99_ms=float(frame_time.get("p99", 0.0)),
        fps_mean=float(fps.get("mean", 0.0)),
        fps_min=float(fps.get("min", 0.0)),
        fps_max=float(fps.get("max", 0.0)),
    )


def parse_memory_metrics(path: Path) -> MemoryMetrics:
    """Parse sampled memory CSV and compute leak-detection statistics."""
    rows: list[tuple[float, float]] = []
    with path.open("r", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            elapsed = float(row["elapsed_seconds"])
            rss_mb = bytes_to_megabytes(int(row["rss_bytes"]))
            rows.append((elapsed, rss_mb))

    if not rows:
        return MemoryMetrics(
            sample_count=0,
            initial_rss_mb=0.0,
            peak_rss_mb=0.0,
            final_rss_mb=0.0,
            growth_rss_mb=0.0,
            slope_mb_per_min=0.0,
            leak_detected=False,
        )

    elapsed_values = [row[0] for row in rows]
    rss_values = [row[1] for row in rows]
    total_duration = elapsed_values[-1] if elapsed_values else 0.0
    warmup_seconds = min(120.0, max(0.0, total_duration * 0.1))
    slope_rows = [row for row in rows if row[0] >= warmup_seconds]
    if len(slope_rows) < 2:
        slope_rows = rows
    slope_x = [row[0] for row in slope_rows]
    slope_y = [row[1] for row in slope_rows]
    slope_mb_per_sec = linear_regression_slope(slope_x, slope_y)
    slope_mb_per_min = slope_mb_per_sec * 60.0

    return MemoryMetrics(
        sample_count=len(rows),
        initial_rss_mb=rss_values[0],
        peak_rss_mb=max(rss_values),
        final_rss_mb=rss_values[-1],
        growth_rss_mb=rss_values[-1] - rss_values[0],
        slope_mb_per_min=slope_mb_per_min,
        leak_detected=slope_mb_per_min > 1.0,
    )


def linear_regression_slope(xs: list[float], ys: list[float]) -> float:
    """Compute simple least-squares slope for y over x."""
    if len(xs) < 2 or len(ys) < 2 or len(xs) != len(ys):
        return 0.0

    mean_x = statistics.fmean(xs)
    mean_y = statistics.fmean(ys)
    numerator = sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ys, strict=True))
    denominator = sum((x - mean_x) ** 2 for x in xs)
    if math.isclose(denominator, 0.0):
        return 0.0
    return numerator / denominator


def bytes_to_megabytes(value: int) -> float:
    """Convert bytes to MiB."""
    return value / (1024.0 * 1024.0)


def print_result_summary(result: ProfileRunResult) -> None:
    """Print concise run summary for terminal consumption."""
    frame = result.frame_metrics
    memory = result.memory_metrics

    print(f"\n=== {result.mode.upper()} PROFILE SUMMARY ===")
    print(
        "Frame time ms: "
        f"mean={frame.frame_time_mean_ms:.3f}, p95={frame.frame_time_p95_ms:.3f}, "
        f"p99={frame.frame_time_p99_ms:.3f}, max={frame.frame_time_max_ms:.3f}"
    )
    print(
        "FPS: "
        f"mean={frame.fps_mean:.2f}, min={frame.fps_min:.2f}, max={frame.fps_max:.2f}"
    )
    print(
        "Memory RSS MiB: "
        f"initial={memory.initial_rss_mb:.2f}, peak={memory.peak_rss_mb:.2f}, "
        f"final={memory.final_rss_mb:.2f}, growth={memory.growth_rss_mb:.2f}, "
        f"slope={memory.slope_mb_per_min:.3f} MB/min, leak={memory.leak_detected}"
    )
    print(f"Frame metrics JSON: {result.frame_metrics_path}")
    print(f"Memory samples CSV: {result.memory_csv_path}")


def main() -> None:
    """Entry point for performance profiling workflow."""
    args = parse_args()

    modes: list[str]
    if args.mode == "both":
        modes = ["source", "packaged"]
    else:
        modes = [args.mode]

    results: list[ProfileRunResult] = []
    for mode in modes:
        duration_seconds = (
            args.source_duration if mode == "source" else args.packaged_duration
        )
        result = run_profile(
            mode=mode,
            duration_seconds=duration_seconds,
            memory_duration_seconds=args.memory_duration,
            memory_interval_seconds=args.memory_interval,
            output_dir=args.output_dir,
            app_binary=args.app_binary,
            seed=args.seed,
        )
        print_result_summary(result)
        results.append(result)

    combined_path = args.output_dir / "combined-summary.json"
    combined_payload = {
        result.mode: {
            "frame_metrics": {
                "duration_seconds": result.frame_metrics.duration_seconds,
                "frame_count": result.frame_metrics.frame_count,
                "frame_time_mean_ms": result.frame_metrics.frame_time_mean_ms,
                "frame_time_max_ms": result.frame_metrics.frame_time_max_ms,
                "frame_time_p95_ms": result.frame_metrics.frame_time_p95_ms,
                "frame_time_p99_ms": result.frame_metrics.frame_time_p99_ms,
                "fps_mean": result.frame_metrics.fps_mean,
                "fps_min": result.frame_metrics.fps_min,
                "fps_max": result.frame_metrics.fps_max,
            },
            "memory_metrics": {
                "sample_count": result.memory_metrics.sample_count,
                "initial_rss_mb": result.memory_metrics.initial_rss_mb,
                "peak_rss_mb": result.memory_metrics.peak_rss_mb,
                "final_rss_mb": result.memory_metrics.final_rss_mb,
                "growth_rss_mb": result.memory_metrics.growth_rss_mb,
                "slope_mb_per_min": result.memory_metrics.slope_mb_per_min,
                "leak_detected": result.memory_metrics.leak_detected,
            },
            "artifacts": {
                "frame_metrics_path": str(result.frame_metrics_path),
                "memory_csv_path": str(result.memory_csv_path),
            },
        }
        for result in results
    }
    combined_path.parent.mkdir(parents=True, exist_ok=True)
    combined_path.write_text(json.dumps(combined_payload, indent=2), encoding="utf-8")
    print(f"\nCombined summary written to: {combined_path}")


if __name__ == "__main__":
    main()
